### ISSUE TITLE
yarn and npm fail on installing phantomjs-prebuilt

### ISSUE THREAD

**Issue by thescientist13** [thegreenhouseio/docker-nodejs-dev#15]
https://circleci.com/gh/thegreenhouseio/angular-webapp-seed/22
```
> phantomjs-prebuilt@2.1.15 install /node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Download already available at /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Verified checksum of previously downloaded file
Extracting tar contents (via spawned process)
Error extracting archive
Phantom installation failed { Error: Command failed: tar jxf /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

    at ChildProcess.exithandler (child_process.js:198:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)
  killed: false,
  code: 2,
  signal: null,
  cmd: 'tar jxf /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2' } Error: Command failed: tar jxf /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

    at ChildProcess.exithandler (child_process.js:198:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12)
npm WARN css-to-string-loader@0.1.3 requires a peer of css-loader@>=0.25.0 <1.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@4.0.2 requires a peer of node-sass@^3.4.2 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@4.0.2 requires a peer of webpack@^1.12.6 || ^2.1.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN tslint-loader@2.1.5 requires a peer of tslint@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-server@1.16.5 requires a peer of webpack@>=1.3.0 <3 but none is installed. You must install peer dependencies yourself.
npm WARN seed-webapp@0.4.0 No description
npm WARN seed-webapp@0.4.0 No repository field.
npm WARN seed-webapp@0.4.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.15 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-10-14T16_46_39_449Z-debug.log
```

This can be reproduced locally from within the container itself

**Comment by thescientist13** [comment]
likely having a fixture as in #9 will be useful to implement to test this

**Comment by thescientist13** [comment]
looks like tar is missing?
```
Phantom installation failed { Error: Command failed: tar jxf /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
```

**Comment by thescientist13** [comment]
Nope, it was **bzip**!
https://github.com/Medium/phantomjs/issues/659#issuecomment-268119362
